config/routes.rb
Rails.application.routes.draw do
  root to: 'albums#index'
  resources :albums
end

app/models/album.rb
class Album < ApplicationRecord
  has_many_attached :images
  validates :title, presence: true
  validates :discription, presence: true
  validate :image_type

  def thumbnail input
    self.images[input].variant(resize: '300x300!').processed
  end

  private
  def image_type
    if images.attached? == false
      errors.add(:images, "are missing!")
    end
    images.each do |image|
      if !image.content_type.in?(%('image/jpeg image/png'))
        errors.add(:image, 'needs to be a JPEG or PNG!')
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :discription, images: [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.slim.erb
= form_with(model: album, local: true) do |form|
  - if album.errors.any?
    #error_explanation
      h2
        = pluralize(album.errors.count, "error")
        | prohibited this album from being saved:
      ul
        - album.errors.full_messages.each do |message|
          li= message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :images
    = form.file_field :images, multiple: true
    br/
  .field
    = form.label :discription
    = form.text_area :discription
  .actions
    = form.submit

app/views/albums/_form.slim
= form_with(model: album, local: true) do |form|
  - if album.errors.any?
    #error_explanation
      h2
        = pluralize(album.errors.count, "error")
        | prohibited this album from being saved:
      ul
        - album.errors.full_messages.each do |message|
          li= message
  .field
    = form.label :title
    = form.text_field :title, :class => "input is-focused mt-2"
  .field
    = form.label :images
    = form.file_field :images, multiple: true, :class => "mt-2"
    br/
  .field
    = form.label :discription
    = form.text_area :discription, :class => "input is-focused mt-2"
  .actions
    = form.submit 'Upload new pictures', :class => "button is-primary mt-4"
= link_to 'Back', albums_path, :class => "button is-hovered mr-4 mt-2"

app/views/albums/edit.html.slim.erb
h1 Editing Album
= render 'form', album: @album
= link_to 'Show', @album
| \
= link_to 'Back', albums_path

app/views/albums/edit.slim
.section
  .container
    h1.subtitle.is-3 Editing Album
    = render 'form', album: @album
    = link_to 'Show', @album, :class => "button is-hovered mt-2"

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Discription</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.title %></td>
        <td><%= album.discription %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/index.slim
p#notice= notice
.section
  .container
    p.title.is-2 Albums

    table.table.is-striped.is-narrow.is-hoverable.is-fullwidth
      thead
        tr
          th Title
          th Discription
          th colspan="3" 
      tbody
        - @albums.each do |album|
          tr
            td = album.title
            td = album.discription
            td = link_to 'Show', album, :class => "button is-info is-light"
            td = link_to 'Edit', edit_album_path(album), :class => "button is-warning is-light"
            td = link_to 'Destroy', album, method: :delete, data: {confirm: 'Are you sure?'}, :class => "button is-danger is-light"
    br
    = link_to 'New Album', new_album_path, :class => "button is-focused"

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path %>

app/views/albums/new.slim
.section
  .container
    h1.subtitle.is-3 New Album
    = render 'form', album: @album

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @album.discription %>
</p>

<%# <div style="width:400px; height:auto"> %>
  <%# <%= link_to image_tag(@album.image, style:'width:100%'), albums_path %> 
<%# </div> %>
<%# <%= image_tag(@album.images, style:'width:400px') %> 
<% (0...@album.images.count).each do |image| %>
  <%= image_tag(@album.thumbnail(image)) %> 
<% end %>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/albums/show.slim
p#notice= notice
.section
  .container
    p.title.is-2
      strong.has-text-grey.mr-4 Title:
      = @album.title
    p.subtitle.is-3
      strong.has-text-grey.mr-4.my-6 Discription:
      = @album.discription

    .columns.is-desktop style="flex-wrap: wrap;"
      - (0...@album.images.count).each do |image|
        = image_tag(@album.thumbnail(image), class:"column is-one-third")

    .w-100
      = link_to 'Edit', edit_album_path(@album), :class => "button is-hovered mr-4"
      = link_to 'Back', albums_path, :class => "button is-hovered"

app/views/layouts/application.html.slim.erb
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title PhotoAlbums2
    = csrf_meta_tags
    = csp_meta_tag
    meta content="width=device-width, initial-scale=1" name="viewport" /
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    title PhotoAlbums
    link href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css" rel="stylesheet" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      .hero.is-dark
        .hero-body
          = link_to 'PhotoAlbums', '/', :class => "title"
      .container
        = yield